package jp.co.example.DbMapper;

import java.util.List;
import jp.co.example.DbMapper.Employee;
import jp.co.example.DbMapper.EmployeeExample;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	long countByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int deleteByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int insert(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int insertSelective(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	List<Employee> selectByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	Employee selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int updateByPrimaryKeySelective(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int updateByPrimaryKey(Employee record);
}