package jp.co.example.DbMapper;

import java.util.List;
import jp.co.example.DbMapper.PurchaseDetail;
import jp.co.example.DbMapper.PurchaseDetailExample;
import jp.co.example.DbMapper.PurchaseDetailKey;
import org.apache.ibatis.annotations.Param;

public interface PurchaseDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	long countByExample(PurchaseDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int deleteByExample(PurchaseDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int deleteByPrimaryKey(PurchaseDetailKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int insert(PurchaseDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int insertSelective(PurchaseDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	List<PurchaseDetail> selectByExample(PurchaseDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	PurchaseDetail selectByPrimaryKey(PurchaseDetailKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int updateByExampleSelective(@Param("record") PurchaseDetail record,
			@Param("example") PurchaseDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int updateByExample(@Param("record") PurchaseDetail record, @Param("example") PurchaseDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int updateByPrimaryKeySelective(PurchaseDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int updateByPrimaryKey(PurchaseDetail record);
}