package jp.co.example.DbMapper;

import java.util.Date;

public class PurchaseSummary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_summary.id
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_summary.customer_id
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_summary.purchase_number
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    private String purchaseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_summary.total_price
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    private Integer totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_summary.purchase_at
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    private Date purchaseAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_summary.id
     *
     * @return the value of purchase_summary.id
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_summary.id
     *
     * @param id the value for purchase_summary.id
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_summary.customer_id
     *
     * @return the value of purchase_summary.customer_id
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_summary.customer_id
     *
     * @param customerId the value for purchase_summary.customer_id
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_summary.purchase_number
     *
     * @return the value of purchase_summary.purchase_number
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    public String getPurchaseNumber() {
        return purchaseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_summary.purchase_number
     *
     * @param purchaseNumber the value for purchase_summary.purchase_number
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    public void setPurchaseNumber(String purchaseNumber) {
        this.purchaseNumber = purchaseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_summary.total_price
     *
     * @return the value of purchase_summary.total_price
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    public Integer getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_summary.total_price
     *
     * @param totalPrice the value for purchase_summary.total_price
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_summary.purchase_at
     *
     * @return the value of purchase_summary.purchase_at
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    public Date getPurchaseAt() {
        return purchaseAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_summary.purchase_at
     *
     * @param purchaseAt the value for purchase_summary.purchase_at
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    public void setPurchaseAt(Date purchaseAt) {
        this.purchaseAt = purchaseAt;
    }
}