package jp.co.example.DbMapper;

import java.util.List;
import jp.co.example.DbMapper.PurchaseSummary;
import jp.co.example.DbMapper.PurchaseSummaryExample;
import org.apache.ibatis.annotations.Param;

public interface PurchaseSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_summary
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    long countByExample(PurchaseSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_summary
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    int deleteByExample(PurchaseSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_summary
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_summary
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    int insert(PurchaseSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_summary
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    int insertSelective(PurchaseSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_summary
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    List<PurchaseSummary> selectByExample(PurchaseSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_summary
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    PurchaseSummary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_summary
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    int updateByExampleSelective(@Param("record") PurchaseSummary record, @Param("example") PurchaseSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_summary
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    int updateByExample(@Param("record") PurchaseSummary record, @Param("example") PurchaseSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_summary
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    int updateByPrimaryKeySelective(PurchaseSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_summary
     *
     * @mbg.generated Sat Dec 16 18:34:48 JST 2017
     */
    int updateByPrimaryKey(PurchaseSummary record);
}