package jp.co.example.DbMapper;

import java.util.Date;

public class PurchaseDetail extends PurchaseDetailKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase_detail.purchase_number
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	private String purchaseNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase_detail.purchase_number_seq
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	private Integer purchaseNumberSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase_detail.item_name
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	private String itemName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase_detail.item_price
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	private Integer itemPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase_detail.purchase_at
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	private Date purchaseAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase_detail.purchase_number
	 * @return  the value of purchase_detail.purchase_number
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	public String getPurchaseNumber() {
		return purchaseNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase_detail.purchase_number
	 * @param purchaseNumber  the value for purchase_detail.purchase_number
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	public void setPurchaseNumber(String purchaseNumber) {
		this.purchaseNumber = purchaseNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase_detail.purchase_number_seq
	 * @return  the value of purchase_detail.purchase_number_seq
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	public Integer getPurchaseNumberSeq() {
		return purchaseNumberSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase_detail.purchase_number_seq
	 * @param purchaseNumberSeq  the value for purchase_detail.purchase_number_seq
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	public void setPurchaseNumberSeq(Integer purchaseNumberSeq) {
		this.purchaseNumberSeq = purchaseNumberSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase_detail.item_name
	 * @return  the value of purchase_detail.item_name
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	public String getItemName() {
		return itemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase_detail.item_name
	 * @param itemName  the value for purchase_detail.item_name
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase_detail.item_price
	 * @return  the value of purchase_detail.item_price
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	public Integer getItemPrice() {
		return itemPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase_detail.item_price
	 * @param itemPrice  the value for purchase_detail.item_price
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	public void setItemPrice(Integer itemPrice) {
		this.itemPrice = itemPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase_detail.purchase_at
	 * @return  the value of purchase_detail.purchase_at
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	public Date getPurchaseAt() {
		return purchaseAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase_detail.purchase_at
	 * @param purchaseAt  the value for purchase_detail.purchase_at
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	public void setPurchaseAt(Date purchaseAt) {
		this.purchaseAt = purchaseAt;
	}
}