package jp.co.example.DbMapper;

import java.util.List;
import jp.co.example.DbMapper.PurchaseDetail;
import jp.co.example.DbMapper.PurchaseDetailExample;
import jp.co.example.DbMapper.PurchaseDetailKey;
import org.apache.ibatis.annotations.Param;

public interface PurchaseDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_detail
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    long countByExample(PurchaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_detail
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    int deleteByExample(PurchaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_detail
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    int deleteByPrimaryKey(PurchaseDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_detail
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    int insert(PurchaseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_detail
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    int insertSelective(PurchaseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_detail
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    List<PurchaseDetail> selectByExample(PurchaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_detail
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    PurchaseDetail selectByPrimaryKey(PurchaseDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_detail
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    int updateByExampleSelective(@Param("record") PurchaseDetail record, @Param("example") PurchaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_detail
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    int updateByExample(@Param("record") PurchaseDetail record, @Param("example") PurchaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_detail
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    int updateByPrimaryKeySelective(PurchaseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_detail
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    int updateByPrimaryKey(PurchaseDetail record);
}