package jp.co.example.DbMapper;

import java.util.List;
import jp.co.example.DbMapper.PurchaseSummary;
import jp.co.example.DbMapper.PurchaseSummaryExample;
import org.apache.ibatis.annotations.Param;

public interface PurchaseSummaryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_summary
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	long countByExample(PurchaseSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_summary
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int deleteByExample(PurchaseSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_summary
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_summary
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int insert(PurchaseSummary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_summary
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int insertSelective(PurchaseSummary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_summary
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	List<PurchaseSummary> selectByExample(PurchaseSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_summary
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	PurchaseSummary selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_summary
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int updateByExampleSelective(@Param("record") PurchaseSummary record,
			@Param("example") PurchaseSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_summary
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int updateByExample(@Param("record") PurchaseSummary record, @Param("example") PurchaseSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_summary
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int updateByPrimaryKeySelective(PurchaseSummary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_summary
	 * @mbg.generated  Wed Aug 29 23:48:34 JST 2018
	 */
	int updateByPrimaryKey(PurchaseSummary record);
}