package jp.co.example.DbMapper;

public class PurchaseDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_detail.id
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_detail.customer_id
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    private Integer customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_detail.id
     *
     * @return the value of purchase_detail.id
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_detail.id
     *
     * @param id the value for purchase_detail.id
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_detail.customer_id
     *
     * @return the value of purchase_detail.customer_id
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_detail.customer_id
     *
     * @param customerId the value for purchase_detail.customer_id
     *
     * @mbg.generated Sat Dec 16 18:23:02 JST 2017
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
}